---
title: "Extraindo os dados"
output: html_notebook
---

```{r, echo=FALSE}
library(tidyverse)
```

Importando os dados

```{r, message=FALSE, warning=FALSE, echo=FALSE}
artigos <- read_csv("ethnicity-gender-cs/papers.csv", col_names = FALSE)
autores <- read_csv("ethnicity-gender-cs/authors.csv", col_names = FALSE)
conferencias <- read_csv("ethnicity-gender-cs/conferences.csv", col_names = FALSE)
etnias <- read_csv("ethnicity-gender-cs/ethnicity.csv", col_names = FALSE)
```

Renomeando colunas:

```{r}
artigos <- artigos %>% 
  rename(
    global_key = X1,
    paper_key = X2,
    conf_key = X3,
    link = X4,
    title = X5,
    pages = X6,
    citations = X7
  )

autores <- autores %>% 
  rename(
    paper_key = X1,
    position_of_author = X2,
    full_name = X3
  )

conferencias <- conferencias %>% 
  rename(
    global_key = X1,
    conf_key = X2,
    year = X3,
    publisher = X4,
    title = X5,
    link = X6,
    cs = X7,
    de = X8,
    se = X9,
    th = X10
  )

etnias <- etnias %>% 
  rename(
    name = X1,
    l0 = X2,
    l1 = X3,
    l2 = X4,
    gender = X5
  )
```

Obtendo número de homens e mulheres para cada área da Ciência da Computação:

```{r}
generos_por_area <- autores %>% 
  left_join(etnias, by = c("full_name" = "name")) %>% 
  left_join(artigos, by = "paper_key") %>% 
  left_join(conferencias, by = "conf_key") %>% 
  filter(gender != "-") %>% 
  select(gender, cs, de, se, th) %>% 
  gather(area, count, cs:th) %>% 
  filter(count == 1) %>% 
  group_by(area, gender) %>% 
  summarise(
    count = n()
  ) %>% 
  spread(gender, count) %>% 
  mutate(
      male_proportion = M / (M + F),
      female_proportion = F / (M + F)
    ) %>%
  gather(gender, proportion, male_proportion:female_proportion) %>% 
  select(-M, -F)

generos_por_area %>% 
  ggplot(aes(x = area, y = proportion, fill = gender)) +
    geom_bar(stat = "identity", position = "dodge")

write_csv(generos_por_area, "generos_por_area.csv")
```

Obtendo a porcentagem dos primeiros autores nos artigos por gênero ao longo dos anos:

```{r}
posicao_por_genero <- autores %>% 
  left_join(etnias, by = c("full_name" = "name")) %>%
  left_join(artigos, by = "paper_key") %>% 
  left_join(conferencias, by = "conf_key") %>% 
  filter(gender != "-", position_of_author == 0) %>% 
  group_by(year) %>% 
  summarise(
    men_count = sum(gender == "M"),
    women_count = sum(gender == "F"),
    men_percentage = men_count / (men_count + women_count),
    women_percentage = women_count / (men_count + women_count)
  ) %>% 
  select(-men_count, -women_count) %>% 
  gather(gender, percentage, men_percentage:women_percentage)

posicao_por_genero %>% 
  ggplot(aes(x = year, y = percentage, color = gender)) +
    geom_line()

write_csv(posicao_por_genero, "posicao_por_genero.csv")
```

```{r}
proporcao_mulheres_por_etnia <- autores %>% 
  left_join(etnias, by = c("full_name" = "name")) %>%
  left_join(artigos, by = "paper_key") %>% 
  left_join(conferencias, by = "conf_key") %>% 
  filter(gender != "-", position_of_author == 0) %>% 
  group_by(year, l2) %>% 
  summarise(
    total = n(),
    women_count = sum(gender == "F"),
    women_proportion = women_count / total
  ) %>% 
  select(-total, -women_count) %>%
  rename(
    ethnicity = l2
  )
  
write_csv(proporcao_mulheres_por_etnia, "proporcao_mulheres_por_etnia.csv")
```

